brew-config:
  orange: 100
  yellow: 100
  pink: 100
  violet: 100
  magenta: 100

  fire: 25
  cold: 25
  acid: 25
  magic: 25
  psionic: 25
  poison: 25
  sharp: 25
  blunt: 25
  pierce: 25
  electricity: 25

  mana: 100
  restore-water: 100
  cure-water: 100
  cyan: 175

spring:
  main:
    allow-circular-references: true
    web-application-type: none

  # SPRING SHELL
  # NOTE: Not sure if these are necessary? Not working on Windows since new shell version.
  shell:
    script:
      enabled: true
    interactive:
      enabled: true
  output:
    ansi:
      enabled: always

  # SQLite DB
  datasource:
    url: jdbc:sqlite:./data/custodian.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

# NOTE: Un-comment for useful logging output.
#logging:
#  level:
#    org.springframework.shell: DEBUG
#    org.hibernate: DEBUG
#    org.springframework: DEBUG
